services:

  db.mysql:
    image: mysql:8.0.40
    container_name: MySQL

  basket.data:
    image: redis:alpine
    container_name: BasketOnRedis

  identity.idp:
    image: eshop/identity
    container_name: Identity
    build:
      context: .
      dockerfile: source/Services/Identity/Dockerfile
    depends_on:
      db.mysql:
        condition: service_healthy

  catalog.api:
    image: eshop/catalog
    container_name: Catalog
    build:
      context: .
      dockerfile: source/Services/Catalog/Dockerfile
    depends_on:
      db.mysql:
        condition: service_healthy
  
  basket.api:
    image: eshop/basket
    container_name: Basket
    build:
      context: .
      dockerfile: source/Services/Basket/Dockerfile
    depends_on:
      basket.data:
        condition: service_healthy

  web.mvc:
    image: eshop/webmvc
    container_name: WebMvc
    build:
      context: .
      dockerfile: source/Web/WebMvc/Dockerfile
    depends_on:
      - catalog.api
