services:

  dbcontext:
    image: mysql:8.0.40
    container_name: MySQL

  identity:
    image: eshop/identity
    container_name: Identity
    build:
      context: .
      dockerfile: source/Services/Identity/Dockerfile
    depends_on:
      dbcontext:
        condition: service_healthy

  catalog:
    image: eshop/catalog
    container_name: Catalog
    build:
      context: .
      dockerfile: source/Services/Catalog/Dockerfile
    depends_on:
      dbcontext:
        condition: service_healthy

  webmvc:
    image: eshop/webmvc
    container_name: WebMvc
    build:
      context: .
      dockerfile: source/Web/WebMvc/Dockerfile
    depends_on:
      - catalog
